### ISSUE TITLE
Objective C version doesn't get prayer times correctly

### ISSUE THREAD

**Issue by SheArRa** [abodehq/Pray-Times#1]
I have used Objective C version to get prayer times according to a certain location, date and timeZone using this method:
-(NSMutableArray_)getDatePrayerTimes:(int)year andMonth:(int)month andDay:(int)day andLatitude:(double)latitude andLongitude:(double)longitude andtimeZone:(double)tZone; as follows:
PrayTime \* pt=[PrayTime new];
double timeZone=[pt getTimeZone];  
NSMutableArray \* prayerTimes=[pt getDatePrayerTimes:2014 andMonth:01 andDay:26 andLatitude:30.056610400000000000 andLongitude:31.330107600000020000 andtimeZone:timeZone];
NSLog(@"PrayerTimes");
for (NSString_ prayTime in prayerTimes) {
    NSLog(@"%@",prayTime);
}
and the result was as follows:
2014-01-26 14:28:07.862 testing[1492:70b] PrayerTimes
2014-01-26 14:28:07.862 testing[1492:70b] 05:35
2014-01-26 14:28:07.863 testing[1492:70b] 06:48
2014-01-26 14:28:07.863 testing[1492:70b] 12:07
2014-01-26 14:28:07.864 testing[1492:70b] 15:06
2014-01-26 14:28:07.865 testing[1492:70b] 17:26
2014-01-26 14:28:07.865 testing[1492:70b] 17:42
2014-01-26 14:28:07.866 testing[1492:70b] 18:30 
but this resultant prayer times isn't correct according to this page:
http://www.islamicfinder.org/cityPrayerNew.php?country=egypt&lang=arabic
also this page
http://www.egynews.net/wps/portal/prayertimes/today
the previous pages gets the prayer times for the same location, date and time zone , i don't know why this happens! is there's a bug in the method or certain  something must be made to get the times correctly? thanks in advance

**Comment by abodehq** [comment]
Elslam Alykom Bro,

I have copied this project from http://praytimes.org as i mentioned in the read me file,you can check their code online,and contact them if something wrong happens.

itis an old time since i worked on this project, but you can run the php sample and play with the your config data till you have the same results.

والله الموفق

**Comment by SheArRa** [comment]
Thanks a lot my brother

**Comment by jabouzi** [comment]
Salam,

Do you still have a problem with the salat times ? I have translated the v1 in C++, Qt, Java and Objective-C and it gives the right times.

**Comment by rizerzero** [comment]
Salam ,  @jabouzi  do you have a c# version , because the one here does not give the correct time for Fajr 
Thank you .

**Comment by jabouzi** [comment]
Salam, @rizerzero  here the source code : https://github.com/jabouzi/salatObjectiveC

**Comment by jabouzi** [comment]
Salam @rizerzero I don't have a c# version.
